### ISSUE TITLE
 error: cast from ‘wxMapMarker*’ to ‘int’ loses precision

### ISSUE THREAD

**Issue by raphael10-collab** [I-CONIC-Vision-AB/wxWebMap#35]
raphy@raohy:~/wxWidgets/wxWebMap$ cmake --build builddir
    -- Configuring done (0.1s)
    -- Generating done (0.0s)
    -- Build files have been written to: /home/raphy/wxWidgets/wxWebMap/builddir
    [  7%] Building CXX object src/CMakeFiles/IconicWebMap.dir/wxMapMarker.cpp.o
    /home/raphy/wxWidgets/wxWebMap/src/wxMapMarker.cpp: In constructor ‘wxMapMarker::wxMapMarker(double, double, bool)’:
    /home/raphy/wxWidgets/wxWebMap/src/wxMapMarker.cpp:13:18: error: cast from ‘wxMapMarker*’ to ‘int’ loses precision [-fpermissive]
       13 |     cLeafletId = (int)this;
          |                  ^~~~~~~~~
    gmake[2]: *** [src/CMakeFiles/IconicWebMap.dir/build.make:104: src/CMakeFiles/IconicWebMap.dir/wxMapMarker.cpp.o] Error 1
    gmake[1]: *** [CMakeFiles/Makefile2:131: src/CMakeFiles/IconicWebMap.dir/all] Error 2
    gmake: *** [Makefile:136: all] Error 2

OS: Ubuntu 23.10

**Comment by HWiman-ICONIC** [comment]
This is a known issue and will be handled. Meanwhile, you can remove the WX option in cxx flags. This will treat the downcast of the pointer as a warning instead of warning and you will be able to compile. Attaching replacements json file.
[CMakePresets.json](https://github.com/I-CONIC-Vision-AB/wxWebMap/files/14123257/CMakePresets.json)

**Comment by raphael10-collab** [comment]
Thank you
